### ISSUE TITLE
Unexpected end-of-input: for file uploads

### ISSUE THREAD

**Issue by robDel01** [brutusin/Brutusin-RPC#11]
"Unexpected end-of-input: was expecting closing quote for a string value\n at [Source: {\"jsonrpc\":\"2.0\",\"params\":{\"image\":\"BrutusinForms; line: 1, column: 99]"

When using the MetaDataInputStream I am getting the above error.

I also cannot access the URL's from the http://demo.rpc.brutusin.org/rpc/repo/#http-services/upload pages

Thanks
Rob

**Comment by idelvall** [comment]
Hi, Rob, three points:
1. Please share your action and javascript invocation code.
2. What browser are you using?
3. What do you mean by you "cannot access the URL's from the link"?

**Comment by robDel01** [comment]
Hi Nacho,

please ignore the issue with the Unexpected EOF - it was a "nut behind the keyboard" error :-)

However using Chrome nothing happens when I click any of the links in the above 

Thanks

**Comment by idelvall** [comment]
Hi, rob, there is only one link above. Try [this](http://demo.rpc.brutusin.org/rpc/repo/#http-services/upload)

**Comment by idelvall** [comment]
I am curious Rob, what client code are you using?

**Comment by robDel01** [comment]
hi, I am using the full stack provided by yourself.
Our client has not yet been developed.

The links are now working, thanks

**Comment by idelvall** [comment]
Ok, let me know if need further help
