### ISSUE TITLE
Validation is not working if form is not filled

### ISSUE THREAD

**Issue by sandeepbhatt** [brutusin/Brutusin-RPC#15]
Hi ,
I am using brutusin:json-forms in my project to create form dynamically. But I have found one issue with validation. If  form is empty then validation is not working for below json 
JSON Data=>
{
    "title": "Person",
    "type": "object",
    "properties": {
        "firstName": {
            "type": "string"
        },
        "lastName": {
            "type": "string"
        },
        "age": {
            "description": "Age in years",
            "type": "integer",
            "minimum": 0
        }
    },
    "required": ["firstName", "lastName"]
}

Please help me to fix this issue.

**Comment by idelvall** [comment]
Sure, can you please post this in the correct project (https://github.com/brutusin/json-forms/issues)?
